---
title: 'Evaluación'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- ¿?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- 

::::::::::::::::::::::::::::::::::::::::::::::::

## Evaluación

En la lección anterior, repasamos cómo los mapas conceptuales nos pueden ayudar a contar conceptos y relaciones para no agotar la memoria de trabajo que puede almacenar 7 mas menos 2 elementos a la vez. También cómo enseñar patrones uniendo varios conceptos en partes del mapa conceptual. Aprendimos la utilidad de los ejercicios desvanecidos. En esta parte vamos a ver otras formas de evaluación.

### ¿Cómo Puedes Saberlo?

Una vez que tengas un mapa conceptual que te muestre lo que quieres enseñar, sentirás la tentación de comenzar a escribir lecciones. Resiste, aún no es el momento. En cambio, lo que debes hacer a continuación es descubrir cómo te darás cuenta si tus estudiantes están aprendiendo. Necesitas un ciclo de retroalimentación que te dirá cuándo puedes seguir adelante, o cuándo tienes que duplicar y volver a explicar algo porque tus estudiantes no lo han entendido o lo han entendido mal.

Para ver cómo hacer esto, imaginemos que enseñas cómo sumar varios dígitos y le pides a tus estudiantes que sumen 37 y 15. Luego de pedirles que hagan el ejercicio, les muestras este ejercicio de opción múltiple.

a. 52
b. 42
c. 412
d. 43

Si dicen "52", entonces entienden cómo hacerlo o han hecho algún error afortunado que les llevó a la respuesta correcta.

Si obtuvieron "42", probablemente no se llevaron el uno. De hecho, probablemente escribieron "12" como la suma de 7 y 5, y luego agregaron 3 y 1 para obtener 4 y escribieron eso sobre el "1" de "12".

¿Qué pasa si tienen 412? En este caso, al sumar las columnas por separado, todavía no entienden cómo llevar, pero es un paso adelante: se quedan con el 1.

¿Y qué hay de 43? Aquí han llevado el 1, pero lo han llevado de vuelta a la columna del 1 porque no entienden que es un 10.

## Diagnóstico de Conceptos Erróneos

Cada estudiante que dio una respuesta incorrecta tiene un concepto erróneo diferente. Por lo tanto, cada uno necesita una explicación diferente para avanzar. Puede ser una progresión lineal o no; lo importante es que si no entiendes lo que ellos no entienden, solo estás adivinando qué decir a continuación.

El uso de preguntas o ejercicios durante la clase para determinar si tus estudiantes están formando los modelos mentales correctos se llama **evaluación formativa**. Esto Da forma al aprendizaje a medida que ocurre.

Las buenas evaluaciones formativas son rápidas (1-2 minutos), para que no descarrilen la enseñanza. No son ambiguas y tienen poder de diagnóstico, lo que significa que te dan una idea de por qué las cosas se han salido de su rumbo. Les dicen a quienes enseñan si pueden seguir adelante o no (y si no, por qué no). Y les brindan a tus estudiantes una forma de verificar que realmente entienden algo (porque es fácil creer que lo hacen hasta que intentan usar el conocimiento).


::::::::::::::::::::::::::::::::::::: challenge 

## Ejercicio

Crea una pregunta de opción múltiple para verificar la comprensión de uno de estos temas. Incluye una respuesta correcta y dos respuestas incorrectas, y explica qué conceptos erróneos deben diagnosticar las respuestas incorrectas.

Duración: 10 minutos
::::::::::::::::::::::::::::::::::::::::::::::::


## Instrucción de Pares



::::::::::::::::::::::::::::::::::::: keypoints 

- Usá archivos `.md` para episodios con contenido estático  
- Usá archivos `.Rmd` para episodios que necesiten generar salidas dinámicas  
- Ejecutá `sandpaper::check_lesson()` para identificar problemas en tu lección  
- Ejecutá `sandpaper::build_lesson()` para previsualizar tu lección localmente

::::::::::::::::::::::::::::::::::::::::::::::::
